import type { Metadata } from "next";
import { ConfigProvider } from "antd";

import "@copilotkit/react-ui/styles.css";
import "antd/dist/reset.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#6d28d9",
              borderRadius: 10,
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
